create table "public"."address" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "street_address1" character varying,
    "street_address2" character varying,
    "postal_code" character varying,
    "city" character varying,
    "country" character varying
);


alter table "public"."address" enable row level security;

create table "public"."property" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" character varying not null,
    "handle" character varying,
    "description" text,
    "sale_type" character varying default 'rent'::character varying,
    "images" character varying[],
    "features" character varying[],
    "price" double precision,
    "property_type" character varying,
    "address" uuid,
    "details" bigint
);


alter table "public"."property" enable row level security;

create table "public"."property_details" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "bathrooms" bigint,
    "bedrooms" bigint,
    "size" bigint,
    "kitchen_status" character varying,
    "property_id" bigint
);


alter table "public"."property_details" enable row level security;

create table "public"."property_type" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" character varying not null
);


alter table "public"."property_type" enable row level security;

CREATE UNIQUE INDEX address_pkey ON public.address USING btree (id);

CREATE UNIQUE INDEX property_details_pkey ON public.property_details USING btree (id);

CREATE UNIQUE INDEX property_handle_key ON public.property USING btree (handle);

CREATE UNIQUE INDEX property_pkey ON public.property USING btree (id);

CREATE INDEX property_price_idx ON public.property USING btree (price);

CREATE UNIQUE INDEX property_type_pkey ON public.property_type USING btree (id);

CREATE UNIQUE INDEX property_type_title_key ON public.property_type USING btree (title);

alter table "public"."address" add constraint "address_pkey" PRIMARY KEY using index "address_pkey";

alter table "public"."property" add constraint "property_pkey" PRIMARY KEY using index "property_pkey";

alter table "public"."property_details" add constraint "property_details_pkey" PRIMARY KEY using index "property_details_pkey";

alter table "public"."property_type" add constraint "property_type_pkey" PRIMARY KEY using index "property_type_pkey";

alter table "public"."property" add constraint "property_handle_key" UNIQUE using index "property_handle_key";

alter table "public"."property" add constraint "public_property_address_fkey" FOREIGN KEY (address) REFERENCES address(id) ON DELETE SET NULL not valid;

alter table "public"."property" validate constraint "public_property_address_fkey";

alter table "public"."property" add constraint "public_property_details_fkey" FOREIGN KEY (details) REFERENCES property_details(id) ON DELETE SET NULL not valid;

alter table "public"."property" validate constraint "public_property_details_fkey";

alter table "public"."property" add constraint "public_property_property_type_fkey" FOREIGN KEY (property_type) REFERENCES property_type(title) not valid;

alter table "public"."property" validate constraint "public_property_property_type_fkey";

alter table "public"."property_details" add constraint "public_property_details_property_id_fkey" FOREIGN KEY (property_id) REFERENCES property(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."property_details" validate constraint "public_property_details_property_id_fkey";

alter table "public"."property_type" add constraint "property_type_title_key" UNIQUE using index "property_type_title_key";

grant delete on table "public"."address" to "anon";

grant insert on table "public"."address" to "anon";

grant references on table "public"."address" to "anon";

grant select on table "public"."address" to "anon";

grant trigger on table "public"."address" to "anon";

grant truncate on table "public"."address" to "anon";

grant update on table "public"."address" to "anon";

grant delete on table "public"."address" to "authenticated";

grant insert on table "public"."address" to "authenticated";

grant references on table "public"."address" to "authenticated";

grant select on table "public"."address" to "authenticated";

grant trigger on table "public"."address" to "authenticated";

grant truncate on table "public"."address" to "authenticated";

grant update on table "public"."address" to "authenticated";

grant delete on table "public"."address" to "service_role";

grant insert on table "public"."address" to "service_role";

grant references on table "public"."address" to "service_role";

grant select on table "public"."address" to "service_role";

grant trigger on table "public"."address" to "service_role";

grant truncate on table "public"."address" to "service_role";

grant update on table "public"."address" to "service_role";

grant delete on table "public"."property" to "anon";

grant insert on table "public"."property" to "anon";

grant references on table "public"."property" to "anon";

grant select on table "public"."property" to "anon";

grant trigger on table "public"."property" to "anon";

grant truncate on table "public"."property" to "anon";

grant update on table "public"."property" to "anon";

grant delete on table "public"."property" to "authenticated";

grant insert on table "public"."property" to "authenticated";

grant references on table "public"."property" to "authenticated";

grant select on table "public"."property" to "authenticated";

grant trigger on table "public"."property" to "authenticated";

grant truncate on table "public"."property" to "authenticated";

grant update on table "public"."property" to "authenticated";

grant delete on table "public"."property" to "service_role";

grant insert on table "public"."property" to "service_role";

grant references on table "public"."property" to "service_role";

grant select on table "public"."property" to "service_role";

grant trigger on table "public"."property" to "service_role";

grant truncate on table "public"."property" to "service_role";

grant update on table "public"."property" to "service_role";

grant delete on table "public"."property_details" to "anon";

grant insert on table "public"."property_details" to "anon";

grant references on table "public"."property_details" to "anon";

grant select on table "public"."property_details" to "anon";

grant trigger on table "public"."property_details" to "anon";

grant truncate on table "public"."property_details" to "anon";

grant update on table "public"."property_details" to "anon";

grant delete on table "public"."property_details" to "authenticated";

grant insert on table "public"."property_details" to "authenticated";

grant references on table "public"."property_details" to "authenticated";

grant select on table "public"."property_details" to "authenticated";

grant trigger on table "public"."property_details" to "authenticated";

grant truncate on table "public"."property_details" to "authenticated";

grant update on table "public"."property_details" to "authenticated";

grant delete on table "public"."property_details" to "service_role";

grant insert on table "public"."property_details" to "service_role";

grant references on table "public"."property_details" to "service_role";

grant select on table "public"."property_details" to "service_role";

grant trigger on table "public"."property_details" to "service_role";

grant truncate on table "public"."property_details" to "service_role";

grant update on table "public"."property_details" to "service_role";

grant delete on table "public"."property_type" to "anon";

grant insert on table "public"."property_type" to "anon";

grant references on table "public"."property_type" to "anon";

grant select on table "public"."property_type" to "anon";

grant trigger on table "public"."property_type" to "anon";

grant truncate on table "public"."property_type" to "anon";

grant update on table "public"."property_type" to "anon";

grant delete on table "public"."property_type" to "authenticated";

grant insert on table "public"."property_type" to "authenticated";

grant references on table "public"."property_type" to "authenticated";

grant select on table "public"."property_type" to "authenticated";

grant trigger on table "public"."property_type" to "authenticated";

grant truncate on table "public"."property_type" to "authenticated";

grant update on table "public"."property_type" to "authenticated";

grant delete on table "public"."property_type" to "service_role";

grant insert on table "public"."property_type" to "service_role";

grant references on table "public"."property_type" to "service_role";

grant select on table "public"."property_type" to "service_role";

grant trigger on table "public"."property_type" to "service_role";

grant truncate on table "public"."property_type" to "service_role";

grant update on table "public"."property_type" to "service_role";


