create table "public"."sale_type" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "value" character varying not null
);


alter table "public"."sale_type" enable row level security;

CREATE UNIQUE INDEX sale_type_pkey ON public.sale_type USING btree (id);

CREATE UNIQUE INDEX sale_type_value_key ON public.sale_type USING btree (value);

alter table "public"."sale_type" add constraint "sale_type_pkey" PRIMARY KEY using index "sale_type_pkey";

alter table "public"."property" add constraint "public_property_sale_type_fkey" FOREIGN KEY (sale_type) REFERENCES sale_type(value) ON DELETE SET NULL not valid;

alter table "public"."property" validate constraint "public_property_sale_type_fkey";

alter table "public"."sale_type" add constraint "sale_type_value_key" UNIQUE using index "sale_type_value_key";

grant delete on table "public"."sale_type" to "anon";

grant insert on table "public"."sale_type" to "anon";

grant references on table "public"."sale_type" to "anon";

grant select on table "public"."sale_type" to "anon";

grant trigger on table "public"."sale_type" to "anon";

grant truncate on table "public"."sale_type" to "anon";

grant update on table "public"."sale_type" to "anon";

grant delete on table "public"."sale_type" to "authenticated";

grant insert on table "public"."sale_type" to "authenticated";

grant references on table "public"."sale_type" to "authenticated";

grant select on table "public"."sale_type" to "authenticated";

grant trigger on table "public"."sale_type" to "authenticated";

grant truncate on table "public"."sale_type" to "authenticated";

grant update on table "public"."sale_type" to "authenticated";

grant delete on table "public"."sale_type" to "service_role";

grant insert on table "public"."sale_type" to "service_role";

grant references on table "public"."sale_type" to "service_role";

grant select on table "public"."sale_type" to "service_role";

grant trigger on table "public"."sale_type" to "service_role";

grant truncate on table "public"."sale_type" to "service_role";

grant update on table "public"."sale_type" to "service_role";


